replicaCount: 1
image:
  repository: "555247716309.dkr.ecr.us-east-1.amazonaws.com/summarizer-llm"
  tag: "0594246feaa35223c6731b9746cb3f3de45ebfcd"
  pullPolicy: IfNotPresent
service:
  port: 11434
  targetPort: 11434
nodeSelector:
  ingress-zone: "1c"
resources:
  limits:
    cpu: "1000m"
    memory: "1024Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"
